version: "3.9"
services:
  traefik:
    image: traefik:v2.9.6
    command:
      --providers.docker=true
      --providers.docker.exposedByDefault=false
      --entryPoints.http.address=:80
    networks:
      - traefik-public
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public

  frontend:
    image: ${REGISTRY:-localhost}/svodd-dev-frontend:cache
    build:
      context: app/frontend/docker
      dockerfile: development/nginx/Dockerfile
      cache_from:
        - ${REGISTRY:-localhost}/svodd-dev-frontend:cache
    networks:
      - traefik-public
      - default
      - rmq-net
    environment:
      APP_ENV: dev
      MAINTENANCE_MODE: 0
      APP_DEBUG: 0
      POSTGRES_HOST: app-postgres
      POSTGRES_USER: app
      POSTGRES_PASSWORD_FILE: /run/secrets/app_db_password
      POSTGRES_DB: app
      MAILER_HOST: mailer
      MAILER_PORT: 1025
      MAILER_USERNAME: app
      MAILER_PASSWORD_FILE: /run/secrets/app_mailer_password
      MAILER_ENCRYPTION: tls
      MAILER_FROM_EMAIL: mail@app.test
      ADMIN_EMAIL: admin@app.test
      COOKIE_DOMAIN: localhost
      URL_SHORTENER_HOST: url-shortener:8000
      URL_SHORTENER_URL: http://url.localhost
      FRONTEND_URL: http://localhost
      STATIC_URL: http://static.localhost
      PARSED_FILES_DIR: /data
      PAGE_SIZE: 50
      CURRENT_QUESTION: 6006
      SENTRY_DSN_FILE: /run/secrets/sentry_dsn
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD_FILE: /run/secrets/redis_password
      RABBIT_HOSTNAME: rmq
      RABBIT_USERNAME: guest
      RABBIT_PASSWORD_FILE: /run/secrets/rabbit_password_file
      RABBIT_EXCHANGE_NAME: ex1
      RABBIT_QUEUE_NAME: q1
      CUT_TELEGRAM_LINKS: 1
    secrets:
      - app_db_password
      - app_mailer_password
      - sentry_dsn
      - redis_password
      - rabbit_password_file
    volumes:
      - ./app:/app
#      - parsed-files:/app/data
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.http.routers.frontend.rule=Host(`localhost`) || Host(`www.localhost`)
      - traefik.http.routers.frontend.entryPoints=http
      - traefik.http.services.frontend.loadBalancer.server.port=80
      - traefik.http.middlewares.frontend-redirect.redirectRegex.regex=^(https?://)www.localhost/(.*)$$
      - traefik.http.middlewares.frontend-redirect.redirectRegex.replacement=$${1}localhost/$${2}
      - traefik.http.middlewares.frontend-redirect.redirectRegex.permanent=true
      - traefik.http.routers.frontend.middlewares=frontend-redirect

#      - traefik.http.routers.frontend-static.rule=Host(`localhost`) || Host(`www.localhost`) && PathPrefix(`/video`)
#      - traefik.http.middlewares.frontend-static-redirect.redirectRegex.regex=^(https?://)(www.)?localhost/video/(.*)$$
#      - traefik.http.middlewares.frontend-static-redirect.redirectRegex.replacement=$${1}static.localhost/video/$${3}
#      - traefik.http.routers.frontend-static.middlewares=frontend-static-redirect

  cli-php:
    image: ${REGISTRY:-localhost}/svodd-dev-cli-php:cache
    build:
      context: app/console/docker
      dockerfile: development/php-cli/Dockerfile
      cache_from:
        - ${REGISTRY:-localhost}/svodd-dev-cli-php:cache
    networks:
      - rmq-net
      - default
    environment:
      APP_ENV: dev
      POSTGRES_HOST: app-postgres
      POSTGRES_USER: app
      POSTGRES_PASSWORD_FILE: /run/secrets/app_db_password
      POSTGRES_DB: app
      MAILER_HOST: mailer
      MAILER_PORT: 1025
      MAILER_USERNAME: app
      MAILER_PASSWORD_FILE: /run/secrets/app_mailer_password
      MAILER_FROM_EMAIL: mail@app.test
      ADMIN_EMAIL: admin@app.test
      FRONTEND_URL: http://localhost
      STATIC_URL: http://static.localhost
      URL_SHORTENER_HOST: url-shortener:8000
      URL_SHORTENER_URL: http://url.localhost
      PARSED_FILES_DIR: /data
      PAGE_SIZE: 50
      CURRENT_QUESTION: 32649
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD_FILE: /run/secrets/redis_password
      RABBIT_HOSTNAME: rmq
      RABBIT_USERNAME: guest
      RABBIT_PASSWORD_FILE: /run/secrets/rabbit_password_file
      RABBIT_EXCHANGE_NAME: ex1
      RABBIT_QUEUE_NAME: q1
    secrets:
      - app_mailer_password
      - app_db_password
      - redis_password
      - rabbit_password_file
    volumes:
      - ./app:/app
      - ./app/data:/app/data

  app-postgres:
    image: postgres:15.1-alpine
    environment:
      APP_ENV: dev
      POSTGRES_USER: app
      POSTGRES_PASSWORD_FILE: /run/secrets/app_db_password
      POSTGRES_DB: app
    secrets:
      - app_db_password
    volumes:
      - app-postgres:/var/lib/postgresql/data
    ports:
      - "54321:5432"

  manticore:
    image: manticoresearch/manticore
    restart: always
    ports:
      - "9306:9306"
      - "9308:9308"
      - "9312:9312"
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
      memlock:
        soft: -1
        hard: -1
    environment:
      searchd_query_log: /var/log/manticore/query.log
    volumes:
      - manticore:/var/lib/manticore
      - manticore:/var/log/manticore
#      - ./dictionary/wordforms.txt:/var/lib/manticore/wordforms.txt
#      - ./dictionary/alternateforms.txt:/var/lib/manticore/alternateforms.txt
#      - ./dictionary/exceptions.txt:/var/lib/manticore/exceptions.txt
#      - ./manticore/manticore.conf:/etc/manticoresearch/manticore.conf

  redis:
    image: redis:7.0.10
    ports:
      - "6379:6379"
    secrets:
      - redis_password
    command: sh -c 'redis-server --save 60 1 --requirepass  "$$(cat /run/secrets/redis_password)"'
    volumes:
      - session-cache:/data

  app-postgres-backup:
    build:
      context: ./app/frontend/docker/common
      dockerfile: postgres-backup/Dockerfile
    environment:
      BACKUP_NAME: fct-search_app-postgres
      POSTGRES_HOST: app-postgres
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD_FILE: /run/secrets/app_db_password
      AWS_ACCESS_KEY_ID: storage_app
      AWS_SECRET_ACCESS_KEY_FILE: /run/secrets/backup_aws_secret_access_key
      AWS_DEFAULT_REGION: region
      S3_ENDPOINT: http://backup-storage:9000
      S3_BUCKET: backup
    secrets:
      - app_db_password
      - backup_aws_secret_access_key
    command: sh -c 'wait-for-it app-postgres:5432 -t 20 && backup'

  mailer:
    image: mailhog/mailhog
    networks:
      - traefik-public
      - default
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.http.routers.mailer.rule=Host(`mailer.localhost`)
      - traefik.http.routers.mailer.entryPoints=http
      - traefik.http.services.mailer.loadBalancer.server.port=8025

  backup-storage:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: storage_app
      MINIO_ROOT_PASSWORD_FILE: /run/secrets/backup_aws_secret_access_key
    secrets:
      - backup_aws_secret_access_key
    volumes:
      - backup-storage:/data
    entrypoint: sh -c 'mkdir -p /data/backup && docker-entrypoint.sh minio server /data --console-address ":80"'
    networks:
      - traefik-public
      - default
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.http.routers.backup-storage.rule=Host(`backup-storage.localhost`)
      - traefik.http.routers.backup-storage.entryPoints=http
      - traefik.http.services.backup-storage.loadBalancer.server.port=80

secrets:
  app_db_password:
    file: ./docker/development/secrets/app_db_password
  app_mailer_password:
    file: ./docker/development/secrets/app_mailer_password
  sentry_dsn:
    file: ./docker/development/secrets/sentry_dsn
  redis_password:
    file: ./docker/development/secrets/redis_password
  backup_aws_secret_access_key:
    file: ./docker/development/secrets/backup_aws_secret_access_key
  rabbit_password_file:
    file: ./docker/development/secrets/rabbit_password_file

volumes:
  app-postgres:
  manticore:
  session-cache:
    driver: local
  backup-storage:

networks:
  traefik-public:
    name: traefik-public
  rmq-net:
    name: rmq-net
