---
- name: Set node labels
  docker_node:
    hostname: "{{ hostname }}"
    labels: "{{ labels }}"
    labels_state: replace

- name: Set node labels2
  docker_node:
    hostname: "{{ hostname2 }}"
    labels: "{{ labels2 }}"
    labels_state: replace
