site:
	ansible-playbook -i hosts.yml site.yml

upgrade:
	ansible-playbook -i hosts.yml upgrade.yml

authorize:
	ansible-playbook -i hosts.yml authorize.yml

docker-login:
	ansible-playbook -i hosts.yml docker-login.yml
