name: Pipeline

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io/audetv
  REGISTRY_HOST: ghcr.io
  IMAGE_TAG: main-${GITHUB_RUN_NUMBER}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Cache APP Composer
        uses: actions/cache@v2
        with:
          path: vendor
          key: app-composer-${{ hashFiles('app/composer.lock') }}

      - name: Docker Login
        uses: azure/docker-login@v1
        with:
            login-server: ${{ env.REGISTRY_HOST }}
            username: audetv
            password: ${{ github.token }}

      - name: Dev Init
        run: make init

      - name: Push dev cache images
        run: make push-dev-cache

      - name: Dev Down
        run: make docker-down-clear

      - name: Build
        run: make build
