name: Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Cache APP Composer
        uses: actions/cache@v2
        with:
          path: app/vendor
          key: app-composer-${{ hashFiles('app/composer.lock') }}

      - name: Dev Init
        run: make init
