name: Pipeline

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io/audetv/fct-search
  REGISTRY_HOST: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Cache APP Composer
        uses: actions/cache@v2
        with:
          path: app/vendor
          key: app-composer-${{ hashFiles('app/composer.lock') }}

      - name: Docker Login
        uses: azure/docker-login@v1
        with:
            login-server: ${{ env.REGISTRY_HOT }}
            username: audetv
            password: ${{ github.token }}

      - name: Dev Init
        run: make init

      - name: Push dev cache images
        run: make push-dev-cache
