name: Pipeline

on: push

env:
  REGISTRY: ghcr.io/audetv
  REGISTRY_HOST: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Cache APP Composer
        uses: actions/cache@v2
        with:
          path: vendor
          key: app-composer-${{ hashFiles('app/composer.lock') }}

      - name: Docker Login
        uses: azure/docker-login@v1
        with:
            login-server: ${{ env.REGISTRY_HOST }}
            username: audetv
            password: ${{ github.token }}

      - name: Dev Init
        run: make init

      - name: Push dev cache images
        run: make push-dev-cache

      - name: Dev Down
        run: make docker-down-clear

      - name: Inject branch slug
        uses: rlespinasse/github-slug-action@v2.x

      - name: Build
        run: make build
        env:
          IMAGE_TAG: ${{ env.GITHUB_REF_SLUG }}-${GITHUB_RUN_NUMBER}

      - name: Push build cache images
        run: make push-build-cache
        env:
          IMAGE_TAG: ${{ env.GITHUB_REF_SLUG }}-${GITHUB_RUN_NUMBER}
